In [1]:
import numpy as np

## Q1
Corresponding equations:
- Total lent out money is $250 million. Thus assuming, all 4 types of loans to be a, b, c, d respectively, we get, a+b+c+d = 250
- First mortgage = 55% of all mortgages. Thus, a = 0.55(a+b) => 45a-55b = 0
- Second mortgage = 25% of all loans. Thus, b = 0.25(a+b+c+d) => a-3b+c+d = 0
- Weighted average interest = 15%. Thus, (14a+20b+20c+10d)/(a+b+c+d)=15 => 14a+20b+20c+10d = 3750 

In [9]:
#creating required matrices
lhs = np.array([[1,1,1,1], [45,-55,0,0], [1,-3,1,1], [14,20,20,10]])
rhs = np.array([250, 0, 0, 3750])

In [10]:
#Solving using matrix inverse
solution = np.linalg.inv(lhs) @ rhs
solution

array([76.38888889, 62.5       , 31.94444444, 79.16666667])

## Loan lent for home improvemnets is 31.94 mn

# Q2

In [48]:
#part1: creating required equations in the form of Xr=y
X = np.array([[-1, 1, 0, 0, 0], [-1, 0, 1, 0, 0], [-1, 0, 0, 1, 0], [-1, 0, 0, 0, 1], [0, 1, -1, 0, 0], [0, 1, 0, -1, 0], 
              [0, 1, 0, 0, -1], [0, 0, 1, -1, 0], [0, 0, -1, 0, 1], [0, 0, 0, -1, 1]])
y = np.array([52-7, 24-21, 38-7, 45-0, 34-16, 25-17, 27-7, 7-5, 30-3, 52-14])

In [49]:
#part2
M = X.T @ X
M

array([[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  4]])

In [51]:
p = X.T @ y
p

array([-124,   91,  -40,  -17,   90])

In [66]:
#part3
M[4,:] = [1,1,1,1,1]
p[4] = 0

r = np.linalg.solve(M,p)
r

array([-24.8,  18.2,  -8. ,  -3.4,  18. ])

In [76]:
#to get team ratings
rankings = {}
for i in range(5):
    rankings[i+1] = r[i]
sort_rankings = sorted(rankings.items(), key=lambda x: x[1], reverse = True)
sort_rankings

[(2, 18.2), (5, 18.0), (4, -3.4), (3, -8.0), (1, -24.8)]

## Second best team is team 5

# Q3



In [22]:
#defining lehmer_entry
def lehmer_entry(i,j):
    if(i>j):
        return j/i
    else:
        return i/j

In [29]:
#creating 4*4 lehmer matrix
matrix = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        matrix[i,j] = lehmer_entry(i+1,j+1)
matrix

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 1.        , 0.66666667, 0.5       ],
       [0.33333333, 0.66666667, 1.        , 0.75      ],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [30]:
#creating 20*20 lehmer matrix
A = np.zeros((20,20))
for i in range(20):
    for j in range(20):
        A[i,j] = lehmer_entry(i+1,j+1)
A

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.5       , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.33333333, 0.66666667, 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ,
        0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.25      , 0.5       , 0.75      , 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ,
        0.36363636, 0.33333333, 0.30769231, 0

In [31]:
#checking if matrix is symmetric
if(A.all() == A.T.all()):
    print("Symmetric")
else:
    print("Non-symmetric")

Symmetric


## Yes the matrice is symmetric

# Q4

In [33]:
#matrix assignment
C = np.linalg.inv(A)
d = [1,2,3,4,5,6,7,8,9,10,10,9,8,7,6,5,4,3,2,1]

In [36]:
#solving for Ax = Cd
x = np.linalg.solve(A,C @ d)
x

array([-8.88178420e-16,  9.94759830e-15,  3.52070682e-15, -7.26913457e-14,
        1.59424384e-13, -2.54373524e-13,  2.73454074e-13, -1.12927026e-13,
       -2.48120301e+01,  2.00642393e+01,  3.58137507e+01, -3.00626280e+01,
       -3.73699569e-04, -2.77204400e-04, -2.09968770e-04, -1.61954093e-04,
       -1.26922825e-04, -1.00877939e-04,  9.50593309e+01, -1.00062903e+02])

In [77]:
#solution for x10
x[9]

20.064239273130674

### x10 = 20.1